services:
  web:
    image: public.ecr.aws/k1g7s6j6/deploy-frontend:latest
    container_name: web
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - DEBUG=1