services:
  web:
    image: public.ecr.aws/g5w5p3f4/frontend-sc-2:latest
    container_name: web
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - DEBUG=1
