services:
  web:
    image: 584839284110.dkr.ecr.eu-north-1.amazonaws.com/deploy-frontend
    container_name: web
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - DEBUG=1
